### ISSUE TITLE
SSL Authentication

### ISSUE THREAD

**Issue by orelmi** [industrial-edge/Apache-Kafka-Connector#7]
I need to implement SSL Authentication. Is there possibility to add keys in Admin and Consumer instances to do that ?

BR

**Comment by Boehmi-TB** [comment]
Please refer to the official developer documentation for Python Confluent Kafka Client
https://github.com/confluentinc/confluent-kafka-python#ssl-certificates

**Comment by orelmi** [comment]
I change this in globalconfig.py

if 'KAFKA' in configJson:
   KAFKA['HOST'] = configJson['KAFKA']['HOST']
   KAFKA['PORT'] = configJson['KAFKA']['PORT']
   KAFKA['SECURITY_PROTOCOL'] = configJson['KAFKA']['SECURITY_PROTOCOL']
   KAFKA['SASL_MECHANISM'] = configJson['KAFKA']['SASL_MECHANISM']
   KAFKA['SASL_USERNAME'] = configJson['KAFKA']['SASL_USERNAME']
   KAFKA['SASL_PASSWORD'] = configJson['KAFKA']['SASL_PASSWORD']
   KAFKA['GROUP_ID'] = configJson['KAFKA']['GROUP_ID']
else:
   print('No Kafka Configuration provided')
   KAFKA['HOST'] = configuration['KAFKA']['HOST']
   KAFKA['PORT'] = configuration['KAFKA']['PORT']
   KAFKA['SECURITY_PROTOCOL'] = configuration['KAFKA']['SECURITY_PROTOCOL']
   KAFKA['SASL_MECHANISM'] = configuration['KAFKA']['SASL_MECHANISM']
   KAFKA['SASL_USERNAME'] = configuration['KAFKA']['SASL_USERNAME']
   KAFKA['SASL_PASSWORD'] = configuration['KAFKA']['SASL_PASSWORD']
   KAFKA['GROUP_ID'] = configuration['KAFKA']['GROUP_ID']
   

and this in kafka.py

`

kwargs = {
    'bootstrap.servers': config.KAFKA['HOST'] + ':' + config.KAFKA['PORT']
    }

if 'SECURITY_PROTOCOL' in config.KAFKA and config.KAFKA['SECURITY_PROTOCOL'] != "":
    kwargs['security.protocol'] = config.KAFKA['SECURITY_PROTOCOL']

if 'SASL_MECHANISM' in config.KAFKA and config.KAFKA['SASL_MECHANISM'] != "":
    kwargs['sasl.mechanism'] = config.KAFKA['SASL_MECHANISM']
    

if 'SASL_USERNAME' in config.KAFKA and config.KAFKA['SASL_USERNAME'] != "":
    kwargs['sasl.username'] = config.KAFKA['SASL_USERNAME']
    

if 'SASL_PASSWORD' in config.KAFKA and config.KAFKA['SASL_PASSWORD'] != "":
    kwargs['sasl.password'] = config.KAFKA['SASL_PASSWORD']

# Create Topic
adminClient = AdminClient(kwargs)
    
`

**Comment by Boehmi-TB** [comment]
Thanks for sharing your implementation SSL Authentication

Currently we are not planning to extend this application example with SSL Authentication. If somebody else requires it we can link your answer in this thread.
